### PR TITLE
Snake body generation works without changing head postions. Body is now trackable. Prettied the code a bit.

### PR DESCRIPTION
**Pull request by SivaramPg**
**CHANGES**
* Changed the snake generation functions up a bit. 
  * It now creates separate head and body tracked individually and hindering each other.
* A direction variable is set on keypress corresponding to the heading direction of the snake head.
* Smaller Changes: 
 * Changed a bit of CSS like the border width is reduced.
 * Few New variables for tracking.
 * Added & Removed some console logs. 
 * Replaced older and now obsolete functions with newer functions with the better functionality.
 * Prettied the code using Prettier extension.

**To-Do**
* Snake body is not animated. 
 * Though snake head move as required without any change in functionality and also clears out the body when it goes over it.
* Add function to check if the snake head has encountered the snake body and act accordingly.

**ISSUES**
* The body currently remains at the position it is generated at.
 * So we can generate multiple bodies at very different positions!
* Shorten the snake when snake head encounters snake body.

### CODE REVIEW

**Comment by ojaswa1942** [comment]
Why is the PR marked as a bug?

**Review by ojaswa1942 — APPROVED** [review]
Everything seems good!
Except, some generalization is required since many things are specifically for first body element! Will begin from there :)

**Comment by SivaramPg** [comment]
Multiple bodies at different places. Need to track last body block and specifically add the body to the last one wherever it might be.

Yeah refactoring code is going to be necessary.
Might be getting a bit messy and confusing. But atleast it works!

**Comment by ojaswa1942** [comment]
No, that's not how we want the body to add

**Pull request merged**
